config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Foodfight::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => 'dashboard'
  resources :categories
  root :to => "home#home_page"

  resources :orders do
    post 'purchase', :on => :member
    get 'confirmation', :on => :member
  end

  resources :order_items

  post "log_out" => "sessions#destroy"
  get "log_in" => "sessions#new"
  get "sign_up" => "users#new"

  resources :users
  resources :sessions
  get "/code" => redirect("https://github.com/JonahMoses/dinner_dash")
  resources :item_categories
  resources :items

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_many :orders
  before_validation :downcase_email

  before_save   :encrypt_password
  with_options :unless => :guest? do |user|
    user.validates_confirmation_of :password
    user.validates_presence_of     :password, :on => :create
    user.validates                 :display_name, length: { in: 2..32 }, :allow_blank => true
    user.validates_presence_of     :email
    user.validates_presence_of     :full_name
    user.validates                 :password, length: { minimum: 6, on: :create }
    user.validates_format_of       :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    user.validates                 :email, :uniqueness => { :case_sensitive => false }
  end

  def self.new_guest
    new { |u| u.guest = true }
  end

  def name
    guest ? "Guest" : email
  end

  def move_to(user)
    orders.update_all(user_id: user.id)
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.new_guest_user_id
    @user = User.new_guest
    return @user.id if @user.save
  end

  def display_name_available?
    if display_name != ""
      display_name
    else
      full_name
    end
  end

private

  def downcase_email
    self.email = self.email.downcase if self.email.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      current_user.move_to(@user) if is_guest?
      session[:user_id] = @user.id
      redirect_to session[:last_order_page] || orders_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
  end

  def is_guest?
    current_user && current_user.guest?
  end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:email, :full_name, :display_name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </p>
  <p>
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/_user_nav.html.erb
<% if current_user %>
  <li><%= link_to "#{current_user.display_name_available?}", edit_user_path(current_user.id) %></li>
  <% if current_user.guest? %>
    <li><%= link_to "Become a member", sign_up_path %></li>
  <% else %>
    <li><%= link_to "Log Out", log_out_path, method: :post %></li>
  <% end %>
<% else %>
  <li><%= link_to "Sign Up", sign_up_path %></li>
  <li><%= link_to "Log In", log_in_path %></li>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>