config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Foodfight::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => 'dashboard'
  resources :categories
  root :to => "home#home_page"

  resources :orders do
    post 'purchase', :on => :member
    get 'confirmation', :on => :member
  end

  resources :order_items

  post "log_out" => "sessions#destroy"
  get "log_in" => "sessions#new"
  get "sign_up" => "users#new"

  resources :users
  resources :sessions
  get "/code" => redirect("https://github.com/JonahMoses/dinner_dash")
  resources :item_categories
  resources :items

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many   :order_items, dependent: :destroy
  has_many   :items, through: :order_items
  belongs_to :user

  def total
    order_items.map(&:subtotal).reduce(:+)
  end

  def items_count
    order_items.map(&:quantity).reduce(:+)
  end

  def self.find_unsubmitted_order_for(user_id)
    where(:status => 'unsubmitted').find_by_user_id(user_id)
  end

  def purchaseable?
    status == "unsubmitted" && user && !user.guest
  end

  def purchase!
    return unless purchaseable?
    update_attributes(:status => "paid")
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :purchase, :confirmation]

  def index
    @orders = current_user.orders.order("created_at DESC")
  end

  def show
  end

  def new
    @order = current_user.orders.new
  end

  def edit
  end

  def create
    @order = current_user.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to items_path }
    end
  end

  def purchase
    if @order.purchaseable?
      @order.purchase!
      session[:order_id] = nil
      redirect_to confirmation_order_path(@order)
    elsif @order.user.guest
      session[:last_order_page] = request.env['HTTP_REFERER'] || orders_path
      redirect_to sign_up_path, notice: "Please sign up to purchase your cart"
    else
      redirect_to @order, notice: "That order is #{@order.status} and can't be purchased.  Please purcahse your current cart."
    end
  end

  def confirmation
  end

  private
    def set_order
      if current_user.admin?
        @order = Order.find(params[:id])
      else
        @order = current_user.orders.find(params[:id])
      end
    end

    def order_params
      params.require(:order).permit(:user_id, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def print_price(price)
    number_to_currency price
  end

end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    Status: <%= f.select :status, ['paid', 'ordered', 'completed', 'cancelled', 'unsubmitted'] %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<tr>
  <td><%= order.status %></td>
  <td class="<%= order.status %>"><%= link_to 'Show', order %></td>
  <% if allow? "orders", "edit" %>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
  <% end %>
  <% if allow? "orders", "destroy" %>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/orders/confirmation.html.erb
<div class="confirmation-banner">
  Confirmation
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table id="order_items_index_table">
  <thead>
    <tr>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <%= render partial: 'orders/order', locals: { order: order } %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table id="order_items_table">
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
  </tr>
  <% @order.order_items.each do |item| %>
    <tr>
      <td><%= item.item.title %></td>
      <td><%= item.item.description %></td>
      <td><%= link_to item.quantity, edit_order_item_path(item), :class => 'item_quantity' %></td>
      <td><%= print_price item.item.price %></td>
      <td><%= print_price item.subtotal %></td>
      <td><%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td><strong>Total:</strong></td>
    <td><%= print_price @order.total %></td>
  </tr>
</table>

<%= link_to "Purchase", purchase_order_path(@order), method: :post %>
<%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete %>
<% if allow? "orders", "edit" %>
  <%= link_to 'Edit', edit_order_path(@order) %>
<% end %>

<%= link_to 'Back', orders_path %>