config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Foodfight::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => 'dashboard'
  resources :categories
  root :to => "home#home_page"

  resources :orders do
    post 'purchase', :on => :member
    get 'confirmation', :on => :member
  end

  resources :order_items

  post "log_out" => "sessions#destroy"
  get "log_in" => "sessions#new"
  get "sign_up" => "users#new"

  resources :users
  resources :sessions
  get "/code" => redirect("https://github.com/JonahMoses/dinner_dash")
  resources :item_categories
  resources :items

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

end

app/views/layouts/_header.html.erb
<div class="row center">
  <%= image_tag("palm_tree1.png", class: "header-images pull-left") %>
  <font style="font-weight: bold; display: inline-block; padding-top: 35px; font-size: 300%; margin-left: 27%;">The Best Hawaiian BBQ</font>
  <%= image_tag("palm_tree2.png", class: "header-images pull-right") %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :class => "alert alert-#{name}",:id => "flash_#{name}" %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Hawaiian BBQ</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Full Menu", items_path %></a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Categories</li>
          <li class="divider"></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li><a href="#">Order History</a></li>
      <li><a href="#">Contact</a></li>
      <% if current_user && current_user.email %>
        <li><%= link_to "My profile", edit_user_path(current_user.id) %></li>
      <% end %>
      <% if current_user && current_user.admin? %>
        <li><%= link_to "Dashboard", dashboard_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Items in cart: #{order_items_count}", orders_path %></a></li>
      <% end %>
      <%= render "users/user_nav" %>
    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodfight</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
</head>
<body>
<div class="container-fluid">

  <div class="col-lg-12">
    <%= render 'layouts/header' %>

    <%= render 'layouts/navbar' %>

    <%= render 'layouts/messages' %>
  </div>

  <div class="col-lg-12">
    <br />
    <%= yield %>
  </div>

</body>
</html>